#!/usr/bin/env python3
"""
Generate HTML report from WA Review Markdown assessment.
Usage: python3 generate-html-report.py wafr-reports/wafr-assessment-YYYY-MM-DD.md
"""

import sys
import re
import json
from pathlib import Path
from datetime import datetime

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AWS Well-Architected Review — {date}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f7fa; color: #1a1a2e; line-height: 1.6; }}
  .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
  header {{ background: linear-gradient(135deg, #232f3e 0%, #37475a 100%); color: white; padding: 40px; border-radius: 12px; margin-bottom: 30px; }}
  header h1 {{ font-size: 2em; margin-bottom: 10px; }}
  header .meta {{ display: flex; gap: 20px; flex-wrap: wrap; font-size: 0.9em; opacity: 0.9; }}
  .score-card {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 30px; }}
  .pillar-card {{ background: white; border-radius: 10px; padding: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); text-align: center; }}
  .pillar-card h3 {{ font-size: 0.9em; color: #666; margin-bottom: 8px; }}
  .pillar-card .score {{ font-size: 2.5em; font-weight: 700; }}
  .pillar-card .stars {{ font-size: 1.2em; color: #ff9900; }}
  .score-5 .score {{ color: #0d9e3f; }}
  .score-4 .score {{ color: #3b82f6; }}
  .score-3 .score {{ color: #f59e0b; }}
  .score-2 .score {{ color: #ef4444; }}
  .score-1 .score {{ color: #991b1b; }}
  .section {{ background: white; border-radius: 10px; padding: 24px; margin-bottom: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .section h2 {{ font-size: 1.3em; margin-bottom: 16px; border-bottom: 2px solid #ff9900; padding-bottom: 8px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #eee; font-size: 0.9em; }}
  th {{ background: #f8f9fa; font-weight: 600; }}
  .severity-critical {{ background: #fee2e2; color: #991b1b; padding: 2px 8px; border-radius: 4px; font-weight: 600; }}
  .severity-high {{ background: #fef3c7; color: #92400e; padding: 2px 8px; border-radius: 4px; font-weight: 600; }}
  .severity-medium {{ background: #e0e7ff; color: #3730a3; padding: 2px 8px; border-radius: 4px; }}
  .severity-low {{ background: #f0fdf4; color: #166534; padding: 2px 8px; border-radius: 4px; }}
  .risk-badge {{ display: inline-block; padding: 4px 12px; border-radius: 20px; font-weight: 600; font-size: 0.85em; }}
  .hri {{ background: #ef4444; color: white; }}
  .mri {{ background: #f59e0b; color: white; }}
  .lri {{ background: #3b82f6; color: white; }}
  footer {{ text-align: center; padding: 20px; color: #666; font-size: 0.85em; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>🏗️ AWS Well-Architected Review</h1>
    <div class="meta">
      <span>📅 {date}</span>
      <span>🔑 Account: {account}</span>
      <span>🌍 Region: {region}</span>
      <span>📊 Framework: General WA (6 Pillars)</span>
    </div>
  </header>

  <div class="score-card">
    {pillar_cards}
  </div>

  <div class="section">
    <h2>📋 Risk Summary</h2>
    <p>
      <span class="risk-badge hri">HRI: {hri_count}</span>
      <span class="risk-badge mri">MRI: {mri_count}</span>
      <span class="risk-badge lri">LRI: {lri_count}</span>
    </p>
  </div>

  <div class="section">
    <h2>🔍 Top Findings</h2>
    <table>
      <thead><tr><th>#</th><th>Finding</th><th>Pillar</th><th>Severity</th></tr></thead>
      <tbody>{findings_rows}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>📄 Full Report</h2>
    <div>{markdown_body}</div>
  </div>

  <footer>
    Generated by AWS Well-Architected Review Skill — {timestamp}
  </footer>
</div>
</body>
</html>"""


def parse_markdown(md_path: str) -> dict:
    """Parse the markdown assessment into structured data."""
    text = Path(md_path).read_text()
    data = {
        'date': datetime.now().strftime('%Y-%m-%d'),
        'account': 'Unknown',
        'region': 'Unknown',
        'pillars': {},
        'findings': [],
        'hri_count': 0, 'mri_count': 0, 'lri_count': 0,
    }

    # Extract metadata
    for line in text.split('\n'):
        if 'Account ID' in line and '|' in line:
            data['account'] = line.split('|')[-2].strip()
        if 'Region' in line and '|' in line and 'Pillar' not in line:
            data['region'] = line.split('|')[-2].strip()
        if 'Assessment Date' in line and '|' in line:
            data['date'] = line.split('|')[-2].strip()

    # Extract pillar scores from scorecard table
    pillar_names = ['Security', 'Ops Excellence', 'Reliability', 'Performance', 'Cost Optimization', 'Sustainability']
    pillar_icons = ['🔒', '⚙️', '🔄', '⚡', '💰', '🌱']
    for i, name in enumerate(pillar_names):
        score_match = re.search(rf'{re.escape(name)}.*?(\d)/5', text)
        score = int(score_match.group(1)) if score_match else 3
        data['pillars'][name] = {'score': score, 'icon': pillar_icons[i]}

    # Count risk levels
    data['hri_count'] = text.lower().count('critical') + text.lower().count('hri')
    data['mri_count'] = text.lower().count('medium')
    data['lri_count'] = text.lower().count('low')

    return data


def generate_html(data: dict, md_text: str) -> str:
    """Generate HTML from parsed data."""
    # Pillar cards
    cards = []
    for name, info in data['pillars'].items():
        stars = '★' * info['score'] + '☆' * (5 - info['score'])
        cards.append(f'''
    <div class="pillar-card score-{info['score']}">
      <h3>{info['icon']} {name}</h3>
      <div class="score">{info['score']}/5</div>
      <div class="stars">{stars}</div>
    </div>''')

    # Simple markdown to HTML (basic)
    md_html = md_text.replace('\n', '<br>\n')
    md_html = re.sub(r'```(\w*)\n(.*?)```', r'<pre><code>\2</code></pre>', md_html, flags=re.DOTALL)
    md_html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', md_html)
    md_html = re.sub(r'#{1,3}\s+(.*?)(<br>)', r'<h3>\1</h3>', md_html)

    return HTML_TEMPLATE.format(
        date=data['date'],
        account=data['account'],
        region=data['region'],
        pillar_cards='\n'.join(cards),
        hri_count=data['hri_count'],
        mri_count=data['mri_count'],
        lri_count=data['lri_count'],
        findings_rows='<tr><td colspan="4">See full report below</td></tr>',
        markdown_body=md_html,
        timestamp=datetime.now().isoformat(),
    )


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate-html-report.py <markdown-file>")
        sys.exit(1)

    md_path = sys.argv[1]
    if not Path(md_path).exists():
        print(f"Error: {md_path} not found")
        sys.exit(1)

    md_text = Path(md_path).read_text()
    data = parse_markdown(md_path)
    html = generate_html(data, md_text)

    out_path = md_path.replace('.md', '.html')
    Path(out_path).write_text(html)
    print(f"HTML report generated: {out_path}")


if __name__ == '__main__':
    main()
