#!/usr/bin/env python3
"""
Generate an HTML report from the Phase-2 weakness-report Markdown.

- Renders Mermaid topology diagrams (```mermaid fenced blocks) via mermaid.js CDN.
- Colors severity badges (🔴/🟠/🟡/🔵/⚪).
- If a sibling findings.json exists, uses it for an accurate summary banner.

Usage:
  python3 generate-html-report.py analysis-output/weakness-report-YYYY-MM-DD.md
"""

import sys
import re
import json
import html as _html
from pathlib import Path
from datetime import datetime

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EKS 自建中间件栈 · 薄弱点分析 — {date}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {{
    if (window.mermaid) {{
      mermaid.initialize({{ startOnLoad: true, theme: "default", securityLevel: "loose" }});
    }}
  }});
</script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', sans-serif; background: #f5f7fa; color: #1a1a2e; line-height: 1.6; }}
  .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
  header {{ background: linear-gradient(135deg, #232f3e 0%, #37475a 100%); color: white; padding: 40px; border-radius: 12px; margin-bottom: 24px; }}
  header h1 {{ font-size: 1.9em; margin-bottom: 10px; }}
  header .meta {{ display: flex; gap: 20px; flex-wrap: wrap; font-size: 0.9em; opacity: 0.92; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 14px; margin-bottom: 24px; }}
  .stat {{ background: white; border-radius: 10px; padding: 18px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); text-align: center; }}
  .stat .n {{ font-size: 2.2em; font-weight: 700; }}
  .stat .l {{ font-size: 0.8em; color: #666; }}
  .n.critical {{ color: #dc2626; }} .n.high {{ color: #ea580c; }}
  .n.medium {{ color: #ca8a04; }} .n.low {{ color: #2563eb; }}
  .badge {{ display:inline-block; padding: 3px 10px; border-radius: 20px; font-weight:600; font-size:0.82em; color:#fff; }}
  .b-fail {{ background:#dc2626; }} .b-ok {{ background:#16a34a; }} .b-na {{ background:#9ca3af; }}
  .content {{ background: white; border-radius: 10px; padding: 28px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .content h1 {{ font-size: 1.6em; margin: 24px 0 12px; }}
  .content h2 {{ font-size: 1.3em; margin: 22px 0 10px; border-bottom: 2px solid #ff9900; padding-bottom: 6px; }}
  .content h3 {{ font-size: 1.1em; margin: 18px 0 8px; color:#37475a; }}
  .content table {{ width: 100%; border-collapse: collapse; margin: 14px 0; }}
  .content th, .content td {{ padding: 8px 10px; text-align: left; border: 1px solid #e5e7eb; font-size: 0.88em; }}
  .content th {{ background: #f8f9fa; font-weight: 600; }}
  .content pre {{ background: #1e293b; color: #e2e8f0; padding: 14px; border-radius: 8px; overflow-x: auto; margin: 12px 0; font-size: 0.85em; }}
  .content code {{ font-family: 'SF Mono', Menlo, monospace; }}
  .content ul, .content ol {{ margin: 10px 0 10px 24px; }}
  .content p {{ margin: 8px 0; }}
  .mermaid {{ background: #fafafa; border: 1px solid #eee; border-radius: 8px; padding: 16px; margin: 16px 0; text-align: center; }}
  footer {{ text-align: center; padding: 20px; color: #666; font-size: 0.85em; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>🧱 EKS 自建中间件栈 · 拓扑与薄弱点分析</h1>
    <div class="meta">
      <span>📅 {date}</span>
      <span>☸️ Cluster: {cluster}</span>
      <span>🌍 Region: {region}</span>
      <span>🧩 组件: {components}</span>
    </div>
  </header>
  <div class="summary">{summary_cards}</div>
  <div class="content">{body}</div>
  <footer>Generated by selfhosted-stack-analyzer — {timestamp}</footer>
</div>
</body>
</html>"""


def load_findings(md_path: Path) -> dict:
    """Load sibling findings.json if present for an accurate summary."""
    fj = md_path.parent / "findings.json"
    if fj.exists():
        try:
            return json.loads(fj.read_text())
        except Exception:
            return {}
    return {}


def md_to_html(md: str) -> str:
    """Minimal but table/mermaid/code-aware Markdown → HTML converter."""
    lines = md.split("\n")
    out = []
    i = 0
    n = len(lines)

    def inline(s: str) -> str:
        s = _html.escape(s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
        return s

    while i < n:
        line = lines[i]

        # fenced code / mermaid
        m = re.match(r"^```(\w*)", line)
        if m:
            lang = m.group(1)
            i += 1
            buf = []
            while i < n and not lines[i].startswith("```"):
                buf.append(lines[i]); i += 1
            i += 1  # skip closing fence
            code = "\n".join(buf)
            if lang == "mermaid":
                out.append(f'<div class="mermaid">\n{_html.escape(code)}\n</div>')
            else:
                out.append(f"<pre><code>{_html.escape(code)}</code></pre>")
            continue

        # table block (consecutive lines containing '|')
        if "|" in line and i + 1 < n and re.match(r"^\s*\|?[\s:\-|]+\|?\s*$", lines[i + 1]):
            header = [c.strip() for c in line.strip().strip("|").split("|")]
            i += 2  # skip header + separator
            rows = []
            while i < n and "|" in lines[i] and lines[i].strip():
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            th = "".join(f"<th>{inline(c)}</th>" for c in header)
            trs = ""
            for r in rows:
                tds = "".join(f"<td>{inline(c)}</td>" for c in r)
                trs += f"<tr>{tds}</tr>"
            out.append(f"<table><thead><tr>{th}</tr></thead><tbody>{trs}</tbody></table>")
            continue

        # headings
        hm = re.match(r"^(#{1,6})\s+(.*)$", line)
        if hm:
            lvl = min(len(hm.group(1)), 3)
            out.append(f"<h{lvl}>{inline(hm.group(2))}</h{lvl}>")
            i += 1
            continue

        # list items (group consecutive)
        if re.match(r"^\s*[-*]\s+", line):
            items = []
            while i < n and re.match(r"^\s*[-*]\s+", lines[i]):
                items.append(inline(re.sub(r"^\s*[-*]\s+", "", lines[i]))); i += 1
            out.append("<ul>" + "".join(f"<li>{it}</li>" for it in items) + "</ul>")
            continue
        if re.match(r"^\s*\d+\.\s+", line):
            items = []
            while i < n and re.match(r"^\s*\d+\.\s+", lines[i]):
                items.append(inline(re.sub(r"^\s*\d+\.\s+", "", lines[i]))); i += 1
            out.append("<ol>" + "".join(f"<li>{it}</li>" for it in items) + "</ol>")
            continue

        # blank / paragraph
        if line.strip() == "":
            i += 1
            continue
        out.append(f"<p>{inline(line)}</p>")
        i += 1

    return "\n".join(out)


def build_summary_cards(f: dict) -> str:
    s = f.get("summary", {}) if f else {}
    fields = [
        ("critical", "CRITICAL"), ("high", "HIGH"),
        ("medium", "MEDIUM"), ("low", "LOW"),
    ]
    cards = []
    for key, label in fields:
        cards.append(
            f'<div class="stat"><div class="n {key}">{s.get(key, "—")}</div>'
            f'<div class="l">{label}</div></div>'
        )
    az = s.get("azFaultTolerant")
    az_txt = "✅ 是" if az is True else ("🔴 否" if az is False else "—")
    cards.append(f'<div class="stat"><div class="n">{az_txt}</div><div class="l">可容忍任一 AZ 故障</div></div>')
    return "\n".join(cards)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate-html-report.py <markdown-file>")
        sys.exit(1)
    md_path = Path(sys.argv[1])
    if not md_path.exists():
        print(f"Error: {md_path} not found")
        sys.exit(1)

    md_text = md_path.read_text()
    findings = load_findings(md_path)
    summ = findings.get("summary", {}) if findings else {}

    # metadata (best-effort from findings.json then markdown)
    cluster = findings.get("cluster", "—")
    region = "—"
    components = "—"
    m = re.search(r"Region\s*\|\s*([^\|]+)\|", md_text)
    if m:
        region = m.group(1).strip()
    if summ.get("componentsAtDataLossRisk"):
        components = ", ".join(summ["componentsAtDataLossRisk"])[:60]

    data = {
        "date": findings.get("analyzedAt", datetime.now().strftime("%Y-%m-%d")),
        "cluster": cluster,
        "region": region,
        "components": components,
        "summary_cards": build_summary_cards(findings),
        "body": md_to_html(md_text),
        "timestamp": datetime.now().isoformat(timespec="seconds"),
    }
    out_path = str(md_path).replace(".md", ".html")
    Path(out_path).write_text(HTML_TEMPLATE.format(**data))
    print(f"HTML report generated: {out_path}")


if __name__ == "__main__":
    main()
